export default [
  { id: 'calendarInvite', icon: 'calendar-plus-o' },
  { id: 'zoomCall', icon: 'video-camera' },
  { id: 'location', icon: 'map-marker', userVisible: true },
  { id: 'carouselProperties', icon: 'th-large' },
  { id: 'carouselFinance', icon: 'th-large' },
  { id: 'carouselPages', icon: 'th-large', userVisible: true },
  { id: 'carouselVideos', icon: 'th-large', userVisible: true },
  { id: 'poll', icon: 'bars', userVisible: true },
  { id: 'file', icon: 'cloud-upload', userVisible: true },
  { id: 'goodNews', icon: 'magic' },
  { id: 'touchpoint2', icon: 'line-chart' },
  { id: 'flightTicketList', icon: 'ticket' },
  { id: 'flightTicket', icon: 'ticket' },
  { id: 'flightSeat', icon: 'plane' },
  { id: 'flightTicketPurchase', icon: 'credit-card' },
  { id: 'flightTicketReceit', icon: 'file-pdf-o' },
  { id: 'e-ticket', icon: 'file-pdf-o' },
  { id: 'profile', icon: 'user-o' }
]
